package GUI;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class JFInicio extends javax.swing.JFrame {
    //banderas que manejan el ingreso de personajes
    private boolean ban1 = false;
    private boolean ban2 = false;
    //raiz de la primer figura
    private estructuras.Raiz_jugador jugador;
    //objetos que se manejan junto a la ventana
    JPFondo_inicio fondo;
    JFJugador ventana1; //personaje jugador planta
    JFJugador ventana2; //personaje jugador zombie
    JFCrear_personaje ventana3;
    
    public JFInicio() {
        initComponents();
        fondo = new JPFondo_inicio();
        this.add(fondo, BorderLayout.CENTER);
        jugador = new estructuras.Raiz_jugador();
        practica1_201020331.Logica_juego.setJugador(jugador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPlantas = new javax.swing.JButton();
        jBZombies = new javax.swing.JButton();
        jBiniciar = new javax.swing.JButton();
        jBresetear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLANTS VS. ZOMBIES");
        setResizable(false);

        jBPlantas.setText("Jugador Plantas");
        jBPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlantasActionPerformed(evt);
            }
        });

        jBZombies.setText("Jugador Zombies");
        jBZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZombiesActionPerformed(evt);
            }
        });

        jBiniciar.setText("Iniciar Juego");
        jBiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiniciarActionPerformed(evt);
            }
        });

        jBresetear.setText("Borrar Datos");
        jBresetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBresetearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBZombies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBresetear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jBPlantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBZombies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBresetear)
                .addGap(151, 151, 151))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlantasActionPerformed
         ventana1 = new JFJugador(jugador, false);
         ventana1.show();
         ban1 = true;
         jBPlantas.setEnabled(false);
    }//GEN-LAST:event_jBPlantasActionPerformed

    private void jBZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBZombiesActionPerformed
        ventana2 = new JFJugador(jugador, true);
        ventana2.show();
        ban2 = true;
        jBZombies.setEnabled(false);
    }//GEN-LAST:event_jBZombiesActionPerformed

    private void jBiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiniciarActionPerformed
        if(ban1 == true && ban2 == true){
        practica1_201020331.Logica_juego.setJugador(jugador);
        ventana3 = new JFCrear_personaje(jugador, false);
        ventana3.show();
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese un jugador "
                    + "de cada tipo");
        }
    }//GEN-LAST:event_jBiniciarActionPerformed

    private void jBresetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBresetearActionPerformed
        jugador.setRaiz_jugador(null);
        jugador.setCola_jugador(null);
        practica1_201020331.Logica_juego.setJugador(jugador);
        jBPlantas.setEnabled(true);
        jBPlantas.setEnabled(true);
    }//GEN-LAST:event_jBresetearActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPlantas;
    private javax.swing.JButton jBZombies;
    private javax.swing.JButton jBiniciar;
    private javax.swing.JButton jBresetear;
    // End of variables declaration//GEN-END:variables
}
