package GUI;

import javax.swing.JOptionPane;

/**
 * @author Cristian
 * CLASE QUE PERMITE MANEJAR NUEVOS JUGADORES 
 * AGREGARLES TAMBIEN EL CAMPO EXTRA DE TEXTO
 */
public class JFJugador extends javax.swing.JFrame {
    //raices de las estructuras que se estan utilizando
    private estructuras.Raiz_jugador raiz_jugador;
    private estructuras.Jugador nuevo_jugador;

    //variable que declara que tipo dde jugador usar
    private boolean tipo;//false es planta y true zombie
    
    public JFJugador(estructuras.Raiz_jugador jugador, boolean t) {
        initComponents();
        this.raiz_jugador = jugador; 
        tipo = t;
        titulo();
        jBextra.setEnabled(false);
    }
    
    public void titulo(){
        if(tipo == false){
            this.setTitle("CREAR JUGADOR PLANTA");
        }else{
            this.setTitle("CREAR JUGADOR ZOMBIE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFnombre = new javax.swing.JTextField();
        jLnombre = new javax.swing.JLabel();
        jLcantidad = new javax.swing.JLabel();
        jTFcantidad = new javax.swing.JTextField();
        jBdatos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBextra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAextra = new javax.swing.JTextArea();
        jBfin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Principales"));

        jLnombre.setText("Nombre");

        jLcantidad.setText("Cantidad");

        jBdatos.setText("aceptar");
        jBdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLnombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLcantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jBdatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcantidad)
                    .addComponent(jTFcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBdatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Campo Extra"));

        jBextra.setText("ingresar");
        jBextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBextraActionPerformed(evt);
            }
        });

        jTAextra.setColumns(20);
        jTAextra.setRows(5);
        jScrollPane1.setViewportView(jTAextra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBextra))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBextra)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jBfin.setText("Finalizar");
        jBfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jBfin)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBfin)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfinActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBfinActionPerformed

    private void jBdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdatosActionPerformed
        try{//en caso que no se ingrese un numero en cantidad
            String nombre = jTFnombre.getText();
            int cantidad = Integer.parseInt(jTFcantidad.getText());
            insertar_jugador(nombre, cantidad);
            jBdatos.setEnabled(false);
            jTFnombre.setEnabled(false);
            jTFcantidad.setEnabled(false);
        }catch(Exception e){ //mostrar el mensje en pantalla
            JOptionPane.showMessageDialog(null, "Ingrese un numero en "
                    + "la casilla cantidad");
        }//fin try
    }//GEN-LAST:event_jBdatosActionPerformed

    private void jBextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBextraActionPerformed
        jBdatos.setVisible(false);
        String texto = jTAextra.getText();
        estructuras.Nodo_extra nuevo = new estructuras.Nodo_extra(texto);
        insertar_extra(nuevo);
        jTAextra.setText("");
    }//GEN-LAST:event_jBextraActionPerformed
    
    /*METODOS DE LA LISTA DEL JUGADOR */
    //metodo para determinar si la raiz del jugador planta esta vacia
    public boolean vacio_jugador(estructuras.Raiz_jugador raiz){
        if(raiz.getRaiz_jugador() != null){
            return false;
        }else{
            return true;
        }
    }
    //insertar al final de la lista todos los valores extra
    public void insertar_jugador(String t, int c){
        nuevo_jugador = new estructuras.Jugador(t, c, tipo);
        if(!vacio_jugador(raiz_jugador)){
            nuevo_jugador.setBack(raiz_jugador.getCola_jugador());
            raiz_jugador.getCola_jugador().setNext(nuevo_jugador);
            raiz_jugador.setCola_jugador(nuevo_jugador);
        }else{
            raiz_jugador.setRaiz_jugador(nuevo_jugador);
            raiz_jugador.setCola_jugador(nuevo_jugador);
        }
    }
    
    public boolean vacio_extra(estructuras.Jugador raiz){
        if(raiz != null){
            return false;
        }else{
            return true;
        }
    }
    
    public void insertar_extra(estructuras.Nodo_extra nuevo){
        if(!vacio_extra(nuevo_jugador)){
            nuevo.setBack(nuevo_jugador.getCola());
            nuevo_jugador.getCola().setNext(nuevo);
            nuevo_jugador.setCola(nuevo);
        }else{
            nuevo_jugador.setRaiz(nuevo);
            nuevo_jugador.setCola(nuevo);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdatos;
    private javax.swing.JButton jBextra;
    private javax.swing.JButton jBfin;
    private javax.swing.JLabel jLcantidad;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAextra;
    private javax.swing.JTextField jTFcantidad;
    private javax.swing.JTextField jTFnombre;
    // End of variables declaration//GEN-END:variables
}
